# Generated by Django 5.1.6 on 2025-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nom', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1500, null=True)),
                ('reference', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=0)),
            ],
        ),
    ]
