# Generated by Django 5.1.6 on 2025-02-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='composant',
            field=models.TextField(null=True),
        ),
    ]
