# Generated by Django 5.1.6 on 2025-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0002_article_composant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='composant',
        ),
    ]
