# Generated by Django 5.1.6 on 2025-02-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0003_composant_remove_article_composant'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='composant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_products.composant'),
        ),
    ]
