# Generated by Django 5.1.6 on 2025-02-14 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0004_article_composant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='composant',
        ),
        migrations.AddField(
            model_name='composant',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_products.article'),
        ),
    ]
