# Generated by Django 5.1.6 on 2025-02-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0005_remove_article_composant_composant_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='stock_products.article'),
        ),
    ]
