# Generated by Django 5.1.6 on 2025-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0006_alter_composant_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
