# Generated by Django 5.1.6 on 2025-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0007_alter_article_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
