# Generated by Django 5.1.6 on 2025-03-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0008_alter_composant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_quantite', models.IntegerField()),
                ('created_at', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleModifier', to='stock_products.article')),
            ],
        ),
    ]
