# Generated by Django 5.1.6 on 2025-03-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0009_articlemodifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodifier',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
