# Generated by Django 5.1.6 on 2025-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0011_alter_articlemodifier_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='composant',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
