# Generated by Django 5.1.6 on 2025-03-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_products', '0013_remove_composant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposantModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_quantite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composantModifier', to='stock_products.composant')),
            ],
        ),
    ]
